### ISSUE TITLE
Trimmed Image not showing up on device

### ISSUE THREAD

**Issue by javalnanda** [wrep/UIImage-Trim#1]
The image is getting trimmed properly on simulator. But the image is not getting displayed in device running on iOS 6.0

**Comment by mac-cain13** [comment]
Hi @javalnanda,

thanks for using UIImage-Trim, I just checked our Apps using this library on iOS 6.0 and the trimming seems to work fine. Could you supply us with an example where the trimming isn't working? Maybe we can spot the error that way!

**Comment by mac-cain13** [comment]
After some more testing everything seems to work fine, please provide some details and reopen this issue if you're still having trouble trimming your images!
